monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: info
      channels:
        - '!deprecation'
        - '!php'
    php:
      type: stream
      path: "%kernel.logs_dir%/php.log"
      level: info
      channels:
        - 'php'
